name: El Colony
favicon: null
layout_spectrum: 0.2688256581313908
typography_spectrum: 0.7974977295380086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#666666'
    - '#9e0000'
    - '#fffefe'
    - '#cfcfcf'
  brandStrength: 0.1875
  lightness: 0.25412576319649816
  saturation: 0.98347630770877
  rhythmicContrast: 0.11931136273778975
purpose: []
